import { writeFile, getRelativePath, getFileNameWithoutExt } from '../utils/fs.js';
import { join, basename } from 'path';
import { logger } from '../utils/logger.js';
import { parseTestResponse, TODOComment } from '../ai/parser.js';

export interface GeneratedTestFile {
  filePath: string;
  content: string;
  sourceFile: string;
  todos: TODOComment[];
  generatedAt: Date;
}

export interface WriteOptions {
  outputDir: string;
  overwrite?: boolean;
  addHeader?: boolean;
}

export class FileWriter {
  private outputDir: string;
  private overwrite: boolean;
  private addHeader: boolean;
  private writtenFiles: GeneratedTestFile[] = [];

  constructor(options: WriteOptions) {
    this.outputDir = options.outputDir;
    this.overwrite = options.overwrite ?? false;
    this.addHeader = options.addHeader ?? true;
  }

  /**
   * Write generated test code to a file
   */
  async writeTestFile(
    sourceFilePath: string,
    testCode: string,
    testFramework: 'vitest' | 'jest'
  ): Promise<GeneratedTestFile> {
    const parsed = parseTestResponse(testCode);
    const testFileName = this.getTestFileName(sourceFilePath, testFramework);
    const testFilePath = join(this.outputDir, testFileName);

    // Check if file exists
    const fs = await import('fs');
    if (fs.existsSync(testFilePath) && !this.overwrite) {
      logger.warn(`Test file already exists: ${testFilePath}. Use --overwrite to replace.`);
      throw new Error(`File exists: ${testFilePath}`);
    }

    // Build file content with header
    let content = parsed.code;
    if (this.addHeader) {
      content = this.addFileHeader(sourceFilePath, parsed.todos, testFramework) + '\n\n' + content;
    }

    // Write file
    writeFile(testFilePath, content);

    const testFile: GeneratedTestFile = {
      filePath: testFilePath,
      content,
      sourceFile: sourceFilePath,
      todos: parsed.todos,
      generatedAt: new Date(),
    };

    this.writtenFiles.push(testFile);
    logger.success(`Generated test file: ${testFilePath}`);

    return testFile;
  }

  /**
   * Get all written files
   */
  getWrittenFiles(): GeneratedTestFile[] {
    return this.writtenFiles;
  }

  /**
   * Get summary of all TODOs
   */
  getAllTODOs(): TODOComment[] {
    return this.writtenFiles.flatMap((file) =>
      file.todos.map((todo) => ({
        ...todo,
        file: file.filePath,
      }))
    );
  }

  /**
   * Create an index file listing all generated tests
   */
  async createIndexFile(): Promise<string> {
    const indexPath = join(this.outputDir, 'index.ts');
    const imports = this.writtenFiles.map((file) => {
      const relativePath = getRelativePath(this.outputDir, file.filePath);
      const moduleName = getFileNameWithoutExt(relativePath);
      return `// ${file.sourceFile}\nimport './${moduleName}';`;
    });

    const content = `/**
 * @generated by AI Test Generator
 * @date ${new Date().toISOString()}
 * @total ${this.writtenFiles.length} test file(s)
 * 
 * This file imports all generated test files.
 * You can remove this file if you prefer to import tests individually.
 */

${imports.join('\n\n')}
`;

    writeFile(indexPath, content);
    logger.info(`Created index file: ${indexPath}`);
    return indexPath;
  }

  private getTestFileName(sourceFilePath: string, _testFramework: 'vitest' | 'jest'): string {
    const fileName = basename(sourceFilePath);
    const nameWithoutExt = getFileNameWithoutExt(fileName);
    const ext = sourceFilePath.endsWith('.tsx') || sourceFilePath.endsWith('.jsx') ? '.tsx' : '.ts';
    return `${nameWithoutExt}.test${ext}`;
  }

  private addFileHeader(
    sourceFilePath: string,
    todos: TODOComment[],
    testFramework: 'vitest' | 'jest'
  ): string {
    const todoCount = todos.length;
    const todoNote = todoCount > 0
      ? ` * @todos ${todoCount} item(s) requiring manual review`
      : ' * @todos None';

    return `/**
 * @generated by AI Test Generator
 * @source ${sourceFilePath}
 * @date ${new Date().toISOString()}
 * @framework ${testFramework}
${todoNote}
 * 
 * Run \`npx ai-test-generator todos\` to list all pending TODOs
 */`;
  }
}

