import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname, basename } from 'path';

export interface GeneratedTest {
  filePath: string;
  content: string;
}

export class TestGenerator {
  private outputDir: string;

  constructor(outputDir: string = '__tests__/generated') {
    this.outputDir = outputDir;
  }

  async writeTests(tests: GeneratedTest[]): Promise<string[]> {
    const writtenFiles: string[] = [];

    // Ensure output directory exists
    if (!existsSync(this.outputDir)) {
      mkdirSync(this.outputDir, { recursive: true });
    }

    for (const test of tests) {
      const fullPath = join(this.outputDir, test.filePath);
      const dir = dirname(fullPath);

      // Ensure subdirectories exist
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      // Write the test file
      writeFileSync(fullPath, test.content, 'utf-8');
      writtenFiles.push(fullPath);
    }

    return writtenFiles;
  }

  formatTestFile(sourceFilePath: string, testCode: string, testFramework: string): GeneratedTest {
    // Generate test file name from source file
    const fileName = basename(sourceFilePath);
    const testFileName = this.getTestFileName(fileName, testFramework);

    // Add header comment
    const header = `// Generated by AI Test Generator
// Source: ${sourceFilePath}
// TODO: Review and adjust tests as needed

`;

    const content = header + testCode;

    return {
      filePath: testFileName,
      content,
    };
  }

  private getTestFileName(sourceFileName: string, testFramework: string): string {
    // Remove extension
    const nameWithoutExt = sourceFileName.replace(/\.(ts|js|tsx|jsx)$/, '');
    
    // Add test suffix based on framework
    if (testFramework === 'vitest') {
      return `${nameWithoutExt}.test.ts`;
    } else {
      return `${nameWithoutExt}.test.ts`;
    }
  }
}
